"""add water tank log

Revision ID: 06e9860e5ed4
Revises: split_customer_name
Create Date: 2026-04-19 21:24:02.225324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06e9860e5ed4'
down_revision = 'split_customer_name'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)

    op.create_table('water_tank_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('gallons', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('returns',
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.sale_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('return_id')
    )
    op.create_table('return_items',
    sa.Column('return_item_id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.return_id'], ),
    sa.PrimaryKeyConstraint('return_item_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('full_name')

    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('middle_initial', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=200), nullable=False))
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('last_name')
        batch_op.drop_column('middle_initial')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('total_amount')
        batch_op.drop_column('preferred_time')
        batch_op.drop_column('delivery_address')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    op.drop_table('return_items')
    op.drop_table('returns')
    op.drop_table('water_tank_log')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
