"""sync models

Revision ID: 09baee1f80f3
Revises: 7733025b81bc
Create Date: 2026-04-22 14:15:46.623733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09baee1f80f3'
down_revision = '7733025b81bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_tank_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_after', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('reference_id', sa.Integer(), nullable=True))
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('water_tank_log_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_tank_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('water_tank_log_ibfk_1'), 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('reference_id')
        batch_op.drop_column('source')
        batch_op.drop_column('level_after')

    # ### end Alembic commands ###
