"""added delivery fields

Revision ID: 12f7fa5e69c7
Revises: 
Create Date: 2026-04-10 10:35:51.539948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12f7fa5e69c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('total_amount')
        batch_op.drop_column('preferred_time')
        batch_op.drop_column('delivery_address')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
